version: "3.7"

services:
  app:
    image: node:12-alpine
    command: sh -c "yarn install && yarn run dev"
    ports:
       - 7000:7000
    working_dir: /app
    volumes:
       - ./:/app
    env_file:
      - .env.staging
    networks:
      - main
    
  db:
      image: postgres
      env_file:
         - .env.staging
      volumes:
         - ./.datadir:/var/lib/postgresql/data
      ports:
         - "5432:5432"
      networks:
         - main
     
networks:
   main:

       